interface PhoneApi {
  ICO: PhoneIcons;
  paintTopRoom(code?: string): void;
  paintTopWho(user?: AuthUser | null): void;
  showToast(message: string): void;
  closeOverlay(id: string): void;
  openOverlay(id: string): void;
  showActionSheet(opts: ActionSheetOpts): Promise<boolean>;
  loadWho(): Promise<void>;
  showPage(name: string, songId?: string | null, push?: boolean): void;
  showDeskPane(name: string): void;
  loadSongs(): Promise<void>;
  loadRoom(): Promise<void>;
  runSearch(page: number, append?: boolean): Promise<void>;
  stopPreview(): void;
  togglePreview(hit: SearchHit, btn: HTMLElement): Promise<void>;
  joinRoom(openScreen?: boolean, quiet?: boolean): Promise<void>;
  openTv(code: string): void;
  paintVocalMix(mix: number): void;
  paintMix(room: Room): void;
  connectRoomRtc(code: string): void;
  ensurePhoneCtx(): AudioContext | null;
  stopPhoneMic(): void;
  paintPhoneMic(): void;
  exitEdit(): void;
  enterEdit(): void;
  ensureTimeline(): LovTimelineHandle | null;
  updateAlignNow(playMs: number): void;
  renderAlignList(): void;
  applyEditorTracks(): void;
  syncEditAxis(): void;
  setPlayIcon(playing: boolean): void;
  refreshPlayIcon(): void;
  unlockPlayerGesture(): void;
  togglePlayer(): void;
  playFromMs(ms: number): void;
  pausePlayer(): void;
  applyKaraokeGain(): void;
  syncGuide(forceTime?: number): void;
  applyPlayerVocalMix(): void;
  hookPlayerAudio(): void;
  loadPlayerList(): Promise<void>;
  loadPlayerSong(songId: string, opts?: LoadPlayerOpts): Promise<void>;
  openPlayer(songId: string): void;
  bootPlayer(): Promise<void>;
  playNextSong(): void;
  cueIndexAt(t: number): number;
  setPlayerSheet(snap: "open" | "peek", anim?: boolean): void;
  enterLearn(): Promise<void> | void;
  exitLearn(): void;
}

interface PhoneState {
  previewId: string;
  searchPage: number;
  searchHits: SearchHit[];
  currentPage: PhonePage | string;
  libState: PhoneLibState;
  libTimer: number;
  libStamp: string;
  libSongs: Song[];
  libLoading: boolean;
  libPages: number;
  searchLoading: boolean;
  searchHasMore: boolean;
  playerSong: Song | null;
  playerLyrics: LyricsDoc;
  selectedCue: number;
  lyricsDirty: boolean;
  playerVocal: number;
  songMediaRev: string;
  playerRaf: number;
  playerHeld: boolean;
  playerHook: BandsHook | null;
  playerViz: BandsViz | null;
  alignTl: LovTimelineHandle | null;
  chainRest: boolean;
  voiceTrackOn: boolean;
  mixTrackOn: boolean;
  playOrder: PlayOrder;
  playerCatalog: Song[];
  playerLoad: number;
  playerClockHold: number | null;
  playerClockHoldAt: number;
  playerHoldDur: number;
  lyricPaint: LyricPaintSlots;
  roomRtc: LovMicSession | null;
  roomRtcCode: string;
  mixTimer: number;
  lyricMode: LyricMode | string;
  nowLanguage: string;
  phoneMic: MediaStream | null;
  phoneMicSrc: MediaStreamAudioSourceNode | null;
  phoneMicGain: GainNode | null;
  phoneCtx: AudioContext | null;
  phoneMicLevel: number;
  phoneIem: boolean;
  phoneNativeLive: boolean;
  phoneStartedTv: boolean;
}
